### ISSUE TITLE
Help with setup please!

### ISSUE THREAD

**Issue by arkadiyk** [symphonyoss/helpdesk-bot#15]
1) https://github.com/symphonyoss/helpdesk-bot/blob/master/proxy-desk/src/main/java/org/symphonyoss/proxydesk/bots/ProxyDeskBot.java#L189 -- Contains hardcoded user name. Should it be configurable? If I leave it as it is it complains that user is not found.

2) I tried to put into that param the name of the Bot I have set up in my Symphony POD. It didn't complain on the startup but when I send anything to the Bot it fails with:

```

2017-04-18 13:50:09 DEBUG MessageService:297 - Failed to retrieve room detail, so this is a chat stream.
org.symphonyoss.exceptions.StreamsException: Failed to obtain room information from ID: pY8DqgWmHbkzpszTN8CYeX___qSgPLrEdA
        at org.symphonyoss.symphony.clients.impl.StreamsClientImpl.getRoomDetail(StreamsClientImpl.java:222)
        at org.symphonyoss.client.services.MessageService.isRoomMessage(MessageService.java:290)
        at org.symphonyoss.client.services.MessageService.onMessage(MessageService.java:219)
```

3) In general relationship between HelpDesk Group and HelpDesk Bot is not clear IMHO. Would be great if there is a bit more details on the Symphony setup and how to refernce the setup from `bot.properties`

Thanks!

**Comment by ftbb** [comment]
commit 1f60a88360b8291771c8f152fa48a27b636856f4
Multiple fixes implemented.

Worked with @arkadiyk to verify build and use.

Please close if satisfied.

**Comment by arkadiyk** [comment]
Everything works now. Thanks a lot!
